# Generated by Django 2.2.5 on 2021-04-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210316_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entered_eniac',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20),
        ),
    ]
