# Generated by Django 2.2.5 on 2021-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210403_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entered_eniac',
            field=models.IntegerField(default=32),
        ),
    ]
