# Generated by Django 2.2.5 on 2021-04-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210422_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=123, max_length=20),
        ),
    ]
