# Generated by Django 2.2.5 on 2021-04-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
