# Generated by Django 2.2.5 on 2021-04-27 01:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default=datetime.datetime(2021, 4, 27, 1, 48, 5, 293837, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
