# Generated by Django 2.2.5 on 2021-04-30 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
