# Generated by Django 2.2.5 on 2021-04-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entered_eniac',
            field=models.CharField(default=32, max_length=10),
        ),
    ]
