# Generated by Django 2.2.5 on 2021-03-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('year', models.DateTimeField()),
                ('cover_image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('교내대회', '교내대회'), ('교외대회', '교외대회')], max_length=20)),
                ('person', models.CharField(default='', max_length=20, verbose_name='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
