# Generated by Django 2.2.5 on 2021-03-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='person',
            field=models.CharField(default='', max_length=20),
        ),
    ]
