# Generated by Django 2.2.5 on 2021-03-18 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_auto_20210312_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='cover_image',
            new_name='image',
        ),
    ]
