# Generated by Django 2.2.5 on 2021-05-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_auto_20210318_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='year',
            field=models.DateField(),
        ),
    ]
