# Generated by Django 2.2.5 on 2021-05-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_auto_20210501_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='year',
            field=models.DateTimeField(),
        ),
    ]
