# Generated by Django 2.2.5 on 2021-05-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='introduce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='motivate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
