# Generated by Django 2.2.5 on 2021-04-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applies', '0002_auto_20210417_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='Motive',
            field=models.TextField(default='1'),
        ),
    ]
