# Generated by Django 2.2.5 on 2021-04-20 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(default='', max_length=20)),
                ('developer', models.CharField(max_length=10)),
                ('explantion', models.TextField(max_length=1000)),
                ('Programing_Language', models.CharField(blank=True, choices=[('Bloop', 'Bloop'), ('BrainF', 'BrainF'), ('QBasic', 'QBasic'), ('Erlang', 'Erlang'), ('Next.js', 'Next.js'), ('TypeScript', 'TypeScript'), ('Dart', 'Dart'), ('Crystal', 'Crystal'), ('Lua', 'Lua'), ('Deno', 'Deno'), ('Clojure', 'Clojure'), ('Haskell', 'Haskell'), ('F#', 'F#'), ('React', 'React'), ('Kotlin', 'Kotlin'), ('Rust', 'Rust'), ('Node.js', 'Node.js'), ('Objective-C', 'Objective-C'), ('Assembly language', 'Assembly_Language'), ('Ruby', 'Ruby'), ('Swift', 'Swift'), ('Go', 'Go'), ('SQL', 'SQL'), ('R', 'R'), ('PHP', 'PHP'), ('JavaScript', 'JavaScript'), ('C#', 'C#'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python'), ('C', 'C')], max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
