# Generated by Django 2.2.5 on 2021-04-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doit',
            name='developer',
        ),
    ]
