# Generated by Django 2.2.5 on 2021-03-16 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doit',
            name='user',
        ),
        migrations.AddField(
            model_name='doit',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
