# Generated by Django 2.2.5 on 2021-04-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doits', '0002_remove_doit_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='doit',
            name='link',
            field=models.URLField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='doit',
            name='개발자',
            field=models.CharField(default='', max_length=10),
        ),
    ]
