# Generated by Django 2.2.5 on 2021-03-16 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doits', '0002_auto_20210316_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doit',
            name='user',
        ),
        migrations.AddField(
            model_name='doit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
