# Generated by Django 2.2.5 on 2021-04-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doits', '0004_auto_20210422_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doit',
            name='category',
            field=models.CharField(choices=[('Web', 'Web'), ('Ai', 'Ai'), ('Game', 'Game'), ('App', 'app'), ('Etc', 'Etc')], max_length=20),
        ),
    ]
