# Generated by Django 2.2.5 on 2021-04-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doits', '0005_auto_20210423_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doit',
            old_name='explantion',
            new_name='explanation',
        ),
    ]
