# Generated by Django 2.2.5 on 2021-05-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doits', '0007_auto_20210423_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doit',
            name='Programing_Language',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('Java', 'Java'), ('Python', 'Python'), ('C#', 'C#'), ('C++', 'C++'), ('JavaScript', 'JavaScript'), ('React', 'React'), ('TypeScript', 'TypeScript'), ('PHP', 'PHP'), ('Kotlin', 'Kotlin'), ('Node.js', 'Node.js'), ('Swift', 'Swift'), ('Assembly language', 'Assembly_Language'), ('Bloop', 'Bloop'), ('BrainF', 'BrainF'), ('QBasic', 'QBasic'), ('Erlang', 'Erlang'), ('Next.js', 'Next.js'), ('Dart', 'Dart'), ('Crystal', 'Crystal'), ('Lua', 'Lua'), ('Deno', 'Deno'), ('Clojure', 'Clojure'), ('Haskell', 'Haskell'), ('F#', 'F#'), ('Rust', 'Rust'), ('Objective-C', 'Objective-C'), ('Ruby', 'Ruby'), ('Go', 'Go'), ('SQL', 'SQL'), ('R', 'R')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doit',
            name='category',
            field=models.CharField(choices=[('Ai', 'AI'), ('App', 'APP'), ('Web', 'WEB'), ('Game', 'GAME'), ('Etc', 'ETC')], max_length=20),
        ),
    ]
