# Generated by Django 2.2.5 on 2021-05-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_lecture_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='link',
            field=models.URLField(max_length=70),
        ),
    ]
