# Generated by Django 2.2.5 on 2021-04-14 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('error', models.TextField()),
                ('explain_situation', models.TextField()),
                ('code', models.TextField()),
                ('OpenSource_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenSourceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('error', models.TextField()),
                ('explain_situation', models.TextField()),
                ('code', models.TextField()),
                ('OpenSourceReview_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('OpenSourceReview_indicated_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_source.OpenSource')),
            ],
            options={
                'verbose_name_plural': 'OpenSourceReview',
            },
        ),
        migrations.AddField(
            model_name='opensource',
            name='OpenSource_host_review',
            field=models.ManyToManyField(to='open_source.OpenSourceReview'),
        ),
    ]
