# Generated by Django 2.2.5 on 2021-04-30 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSourceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('error', models.TextField()),
                ('explain_situation', models.TextField()),
                ('code', models.TextField()),
                ('OpenSourceReview_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'OpenSourceReview',
            },
        ),
        migrations.CreateModel(
            name='OpenSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=40)),
                ('error', models.TextField()),
                ('explain_situation', models.TextField()),
                ('code', models.TextField()),
                ('error_signal', models.BooleanField(default='False')),
                ('OpenSource_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('OpenSource_host_review', models.ManyToManyField(to='open_source.OpenSourceReview')),
                ('code_Language', models.ManyToManyField(related_name='code_language', to='studies.LanguageType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
