# Generated by Django 2.2.5 on 2021-04-15 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_source', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opensourcereview',
            name='OpenSourceReview_indicated_host',
        ),
    ]
