# Generated by Django 2.2.5 on 2021-04-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_source', '0003_opensource_code_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensource',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
    ]
