# Generated by Django 2.2.5 on 2021-04-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_source', '0005_opensource_complet_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opensource',
            old_name='complet_error',
            new_name='complete_error',
        ),
    ]
