# Generated by Django 2.2.5 on 2021-04-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_source', '0006_auto_20210422_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opensource',
            old_name='complete_error',
            new_name='error_signal',
        ),
    ]
