# Generated by Django 2.2.5 on 2021-04-10 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'LanguageType',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Study_Name', models.CharField(max_length=70)),
                ('Leader', models.CharField(max_length=70)),
                ('Recruit_Member_Number', models.IntegerField()),
                ('Deadline', models.BooleanField(default=False)),
                ('Title_Intro', models.TextField(blank=True, null=True)),
                ('Introduce', models.TextField(blank=True, null=True)),
                ('Learning_Cycle', models.CharField(blank=True, max_length=70, null=True)),
                ('Deadline_Date', models.DateField(blank=True, null=True)),
                ('Programing_Language', models.ManyToManyField(related_name='language', to='studies.LanguageType')),
                ('Room_Host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Room_Member', models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
