# Generated by Django 2.2.5 on 2021-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagetype',
            name='language_genre',
            field=models.CharField(blank=True, choices=[('web', 'Web'), ('app', 'app'), ('machine_learning', 'machine_learning'), ('game', 'game')], max_length=80, null=True),
        ),
    ]
