# Generated by Django 2.2.5 on 2021-04-17 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='Image',
            field=models.ImageField(default=datetime.datetime(2021, 4, 17, 13, 38, 44, 39636, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
