# Generated by Django 2.2.5 on 2021-05-01 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_study_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='study_genre',
            field=models.CharField(choices=[('Web', 'Web'), ('App', 'App'), ('Machine_Learning', 'Machine_Learning'), ('Game', 'Game'), ('Etc', 'Etc')], default=datetime.datetime(2021, 5, 1, 8, 12, 6, 477560, tzinfo=utc), max_length=79),
            preserve_default=False,
        ),
    ]
