# Generated by Django 2.2.5 on 2021-04-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_remove_languagetype_language_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='study_genre',
            field=models.CharField(choices=[('Web', 'Web'), ('App', 'App'), ('machine_learning', 'machine_learning'), ('game', 'game')], default='Web', max_length=79),
        ),
    ]
