# Generated by Django 2.2.5 on 2021-05-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_study_study_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='Programing_Language',
            field=models.ManyToManyField(blank=True, null=True, related_name='language', to='studies.LanguageType'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_genre',
            field=models.CharField(blank=True, choices=[('Web', 'Web'), ('App', 'App'), ('Machine_Learning', 'Machine_Learning'), ('Game', 'Game'), ('Etc', 'Etc')], max_length=79, null=True),
        ),
    ]
