# Generated by Django 2.2.5 on 2021-05-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_auto_20210501_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='Programing_Language',
            field=models.ManyToManyField(blank=True, related_name='language', to='studies.LanguageType'),
        ),
    ]
