# Generated by Django 2.2.5 on 2021-05-15 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_auto_20210501_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='Deadline_Date',
        ),
    ]
