# Generated by Django 3.2.3 on 2021-05-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_remove_study_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='study_genre',
            field=models.CharField(blank=True, choices=[('Web', 'Web'), ('App', 'App'), ('AI', 'AI'), ('Game', 'Game'), ('major', 'major')], max_length=79, null=True),
        ),
    ]
